# Generated by Django 5.1.2 on 2024-12-22 16:09

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('school', '0003_remove_student_teacher_student_teachers'),
    ]

    operations = [
        migrations.CreateModel(
            name='StudentTeahers',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('student', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='student_teachers', to='school.student')),
                ('teacher', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='student_teachers', to='school.teacher')),
            ],
            options={
                'verbose_name': 'Связь ученика с учителем',
                'verbose_name_plural': 'Связи учеников с учителями',
            },
        ),
    ]
