# Generated by Django 5.1.2 on 2024-12-22 16:16

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('school', '0004_studentteahers'),
    ]

    operations = [
        migrations.DeleteModel(
            name='StudentTeahers',
        ),
    ]
